---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin-system

resources:
  - ./deployment.yaml
  - ./namespace.yaml
  - ./ingress.yaml
  - ./service.yaml

  - ./jellyfin-pvc.yaml
  - ./movies-pvc.yaml
  - ./shows-pvc.yaml
