---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: paperless-redis
spec:
  # Standalone: 1 instance total
  replicas: 1

  authentication:
    passwordFromSecret:
      name: paperless-redis-auth
      key: password

  # Optional: create a stable service name you can reference from Paperless
  serviceSpec:
    name: paperless-redis
    type: ClusterIP

  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

  # Persistence: snapshots stored on a PVC (operator-managed)
  snapshot:
    persistentVolumeClaimSpec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
