---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: jellyfin
spec:
  image: "ghcr.io/jellyfin/jellyfin"
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: jellyfin
spec:
  imageRepositoryRef:
    name: jellyfin
  policy:
    semver:
      range: ">=10.10.0"
