---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiobookshelf

resources:
  - ../../../bases/audiobookshelf
  - ./ingress.yaml

patches:
  - path: version.yaml
    target:
      kind: Deployment
      name: audiobookshelf
