---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-nfs-media
spec:
  storageClassName: ""
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: totoro.lan
    path: /Documents/Paperless
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media
spec:
  storageClassName: ""
  volumeName: paperless-nfs-media
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Gi
