---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden

resources:
  - ../../../bases/vaultwarden

  - ./ingress.yaml
  - ./admin-token.yaml

patches:
  - path: version.yaml
    target:
      kind: Deployment
  - path: ./envFrom.yaml
    target:
      kind: Deployment
