apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web
spec:
  template:
    spec:
      containers:
        - name: calibre-web
          image: ghcr.io/linuxserver/calibre-web:0.6.24-ls315 # {"$imagepolicy": "apps-system:calibre-web"}
