---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-books
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
