---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie

resources:
  - ../../../bases/mealie

patches:
  - path: version.yaml
    target:
      kind: Deployment
      name: mealie
