apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  template:
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v2.5.0 # {"$imagepolicy": "apps-system:mealie"}
