---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: vaultwarden
spec:
  image: "ghcr.io/dani-garcia/vaultwarden"
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: vaultwarden
spec:
  imageRepositoryRef:
    name: vaultwarden
  policy:
    semver:
      range: ">=1.33.0"
