---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: finances-controllers
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 30s
  timeout: 30s
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-apps
  path: components/finances/controllers/envs/${ENVIRONMENT}
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
