---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-nfs-shows
spec:
  storageClassName: ""
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: totoro.lan
    path: /Shows
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc-shows
spec:
  storageClassName: ""
  volumeName: jellyfin-pv-nfs-shows
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Ti
