apiVersion: v1
kind: Secret
metadata:
    name: actual-server
stringData:
    username: ENC[AES256_GCM,data:u8vlVjqnj95jFGSDBYrWQEXJ2J9K,iv:AiULXj8XubZW5PgcRvx/2rBx42ZUq8o1wUPnCsxpnPw=,tag:NEhgAQR/FdYY7F6vhVQWIg==,type:str]
    password: ENC[AES256_GCM,data:E0OM1NzZdMeoxZPXYKrXkcwH59G5nfT7wtfiucoyUNcR94PY1Oi/1FHnTxFQbwjWYAbJuGp93CpWryw0JMgp+aUWX4VD8dqkuQpK+X54AUlBtgVqZHPoeXkAwQd/,iv:+tpU3dqnCoEixPQYwThNvKEv+nWyKkvFoxk2bNQ3M8M=,tag:HQ0LOM3dT3X30CwPbSmV8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w25xrwp4207snq0nr7ext6slkph3n5zw0u6t358k46p7v9zx0udstxpw5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMkpxSzdxZVNCWGdER3pP
            bkhCV2pxQ0ZodnpVMHQ3UUhLcXBNRVJCam1ZClMzMTBINExvOVFSa2hhc3VXczBq
            MFdPUzQ3VkxsR2FyVzB0cjBqV1VZRUEKLS0tIGYxNjd2dmhIL0ZKUERIZmxEcUhi
            VlpiVUl4Z0diTzZ3U3J6MGRHY1J6RjQKIfTrDgjbT04mQITN2srjlpuXgXnbrPnZ
            9fjYL+Rk8+tC8NbiT+4fj/Dd1WAz4P5oBe3NIRdQKYz3ond/b1VBoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T22:48:38Z"
    mac: ENC[AES256_GCM,data:/QJqzXy11lNN9023GA5scrCrs3/sK+l3jNMCXRIJFSMQF8ub5dmHinK/FuL75KnMNbmRaravx4Eefg588fMELYONgBQnqV/RT+soeVCUxPGJY2RVToZHV7KHwNx7G9GaXvJzjAa2wN/RAMzhII9jwRVUmtqOX3xNx8M3ZJ10h3I=,iv:7e4qjb/9eq4kKGziJHphd1ZHu5GMBijy7di7HIpwdls=,tag:zcQiWv7OrHyM9uII352LDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: actual-server
spec:
    interval: 1m0s
    url: https://github.com/cleroux-dev-homelab/flux-apps.git
    ref:
        branch: main
    secretRef:
        name: actual-server
    ignore: |
        /*
        !/components/finances/actual-server
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w25xrwp4207snq0nr7ext6slkph3n5zw0u6t358k46p7v9zx0udstxpw5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMkpxSzdxZVNCWGdER3pP
            bkhCV2pxQ0ZodnpVMHQ3UUhLcXBNRVJCam1ZClMzMTBINExvOVFSa2hhc3VXczBq
            MFdPUzQ3VkxsR2FyVzB0cjBqV1VZRUEKLS0tIGYxNjd2dmhIL0ZKUERIZmxEcUhi
            VlpiVUl4Z0diTzZ3U3J6MGRHY1J6RjQKIfTrDgjbT04mQITN2srjlpuXgXnbrPnZ
            9fjYL+Rk8+tC8NbiT+4fj/Dd1WAz4P5oBe3NIRdQKYz3ond/b1VBoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T22:48:38Z"
    mac: ENC[AES256_GCM,data:/QJqzXy11lNN9023GA5scrCrs3/sK+l3jNMCXRIJFSMQF8ub5dmHinK/FuL75KnMNbmRaravx4Eefg588fMELYONgBQnqV/RT+soeVCUxPGJY2RVToZHV7KHwNx7G9GaXvJzjAa2wN/RAMzhII9jwRVUmtqOX3xNx8M3ZJ10h3I=,iv:7e4qjb/9eq4kKGziJHphd1ZHu5GMBijy7di7HIpwdls=,tag:zcQiWv7OrHyM9uII352LDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
