---
apiVersion: v1
kind: Service
metadata:
  name: actual-server
spec:
  selector:
    app: actual-server
  type: ClusterIP
  ports:
    - name: https
      protocol: TCP
      port: 5006
      targetPort: https
