---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: calibre-web
spec:
  targetNamespace: calibre-web
  interval: 1m0s
  retryInterval: 30s
  timeout: 30s
  path: ./kustomize
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: calibre-web
