---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: mealie
spec:
  image: "ghcr.io/mealie-recipes/mealie"
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: mealie
spec:
  imageRepositoryRef:
    name: mealie
  policy:
    semver:
      range: ">=v2.0.0"
