apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: calibre-web
spec:
  targetNamespace: calibre-web
  interval: 1m0s
  retryInterval: 30s
  timeout: 30s
  path: components/books/controllers/bases/calibre-web
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: books-controllers
  images:
    - name: calibre-web
      newName: ghcr.io/linuxserver/calibre-web # {"$imagepolicy": "calibre-web:calibre-web:name"}
      newTag: 0.6.23-ls296 # {"$imagepolicy": "calibre-web:calibre-web:tag"}
