apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
spec:
  targetNamespace: jellyfin
  interval: 1m0s
  retryInterval: 30s
  timeout: 30s
  path: components/media/controllers/bases/jellyfin
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: media-controllers
  images:
    - name: jellyfin
      newName: ghcr.io/linuxserver/jellyfin # {"$imagepolicy": "jellyfin:jellyfin:name"}
      newTag: 0.6.23-ls296 # {"$imagepolicy": "jellyfin:jellyfin:tag"}
