---
apiVersion: v1
kind: Namespace
metadata:
  name: mealie
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mealie
  namespace: mealie
spec:
  interval: 1m0s
  url: https://github.com/cleroux-dev-homelab/mealie.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mealie
  namespace: mealie
spec:
  targetNamespace: mealie
  interval: 1m0s
  retryInterval: 30s
  timeout: 30s
  path: ./kustomize
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: mealie
