---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: audiobookshelf
spec:
  image: ghcr.io/advplyr/audiobookshelf
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: audiobookshelf
spec:
  imageRepositoryRef:
    name: audiobookshelf
  policy:
    semver:
      range: ">=2.21.0"
