apiVersion: v1
kind: Secret
metadata:
    name: jellyfin
stringData:
    username: ENC[AES256_GCM,data:f+gU6uFCK+c6uU7FemT6P0+PaR9f,iv:Kl9alF2qyNa9Htz1V9rgvAyWZQSWuvfQgfI+0cW0248=,tag:tzWDyPHBm8osv3YoJ9aT/Q==,type:str]
    password: ENC[AES256_GCM,data:xTVewolDN08P9TrMyQ23uumqazk1j8mOFNYBHbttgDA0ULORWx7Yj6TWabEvCTlImW4707j2za6PuIBivg5nBBRZ629nmc+MCRAb00NyalivljtjM+dnyxxL6Iql,iv:eLKQpWyUpMup3mip013mg/ixUDs4y+13QedUi3/dUDs=,tag:/X76lJPzhK6xNgKydmz10A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w25xrwp4207snq0nr7ext6slkph3n5zw0u6t358k46p7v9zx0udstxpw5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dUk4c1pSMTh5T3ZpRVRD
            WVp4RkxkQ2lJYUpKc3R4Vk1vcURZVzdYQjA4Cmh5VE5xS2toSGgrOXl0ck1qZVIy
            L3o0OW10KzZNRjZCcG12MW54Nk9qaWMKLS0tIGRLa2FBSVZZL1lrZ0t6emJWTHBk
            TkFZeElTWk5ZVGJBNWlVcEVlOFhuT0EKb23934DBw+rgSc5zAQ4RNQqESK+LGz5g
            NIpfb60Kpbhx4gMFbieRioULIhZnJEdDpwCABXIJFkE5nR/dzpu8rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T22:48:34Z"
    mac: ENC[AES256_GCM,data:NFOtPYIwcYtJ9V/Pi3uPzzpWuiPKDZ+6WcEkvdLA9+4zhriYN81u7CK+dkr4P7YcO2uSgN6OGiroeGS70vesC+UbOQCFlHifuBe7YPVvqZ7S0UhzUzlulgfJhY9abz3ZDvuuAmezJPIYVzzOuQyrqxSqsvzfBf7Ln7H/OeZY+CQ=,iv:hGvhO/X8guYX2aBrP2BeWSe3VVbOFjhCMWcgw3kr2qE=,tag:paj7E9xgMK7WJZY5IcW0tA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: jellyfin
spec:
    interval: 1m0s
    url: https://github.com/cleroux-dev-homelab/flux-apps.git
    ref:
        branch: main
    secretRef:
        name: jellyfin
    ignore: |
        /*
        !/components/media/jellyfin
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w25xrwp4207snq0nr7ext6slkph3n5zw0u6t358k46p7v9zx0udstxpw5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dUk4c1pSMTh5T3ZpRVRD
            WVp4RkxkQ2lJYUpKc3R4Vk1vcURZVzdYQjA4Cmh5VE5xS2toSGgrOXl0ck1qZVIy
            L3o0OW10KzZNRjZCcG12MW54Nk9qaWMKLS0tIGRLa2FBSVZZL1lrZ0t6emJWTHBk
            TkFZeElTWk5ZVGJBNWlVcEVlOFhuT0EKb23934DBw+rgSc5zAQ4RNQqESK+LGz5g
            NIpfb60Kpbhx4gMFbieRioULIhZnJEdDpwCABXIJFkE5nR/dzpu8rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T22:48:34Z"
    mac: ENC[AES256_GCM,data:NFOtPYIwcYtJ9V/Pi3uPzzpWuiPKDZ+6WcEkvdLA9+4zhriYN81u7CK+dkr4P7YcO2uSgN6OGiroeGS70vesC+UbOQCFlHifuBe7YPVvqZ7S0UhzUzlulgfJhY9abz3ZDvuuAmezJPIYVzzOuQyrqxSqsvzfBf7Ln7H/OeZY+CQ=,iv:hGvhO/X8guYX2aBrP2BeWSe3VVbOFjhCMWcgw3kr2qE=,tag:paj7E9xgMK7WJZY5IcW0tA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
