---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin-system

resources:
  - ../../../bases/jellyfin

patches:
  - path: version.yaml
    target:
      kind: Deployment
      name: jellyfin
