apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  template:
    spec:
      containers:
        - name: jellyfin
          image: jellyfin # {"$imagepolicy": "apps-system:jellyfin"}
