---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: calibre-web

resources:
  - ../../../bases/calibre-web

  - ./ingress.yaml

patches:
  - path: version.yaml
    target:
      kind: Deployment
      name: calibre-web
