---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-pg
spec:
  instances: 1
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
      secret:
        name: paperless-db-app-user
