apiVersion: v1
kind: Secret
metadata:
    name: calibre-web
stringData:
    username: ENC[AES256_GCM,data:GXFRImDFt4Ouh3ElS0s39hKNXeL+,iv:QTc4oydnZPxU/b8Vhv9txRnETl6C1fFxZtSH16Gq1zA=,tag:s133Fld3vJJANmVYoHio3Q==,type:str]
    password: ENC[AES256_GCM,data:0779rsDY+GRM/5JoOawpaooNB8viF+S7u1bR88B3eThbKOA63WvLfq9bDAGhFX2HMd+arvHgcsGeAu3hQo4x5oEDAMFfazML4AitAk9htDhj6MSz7aSRNU3OeKoq,iv:xkXeibanowU40Hs9HbslYfe1a0ZXw33lu4oh8mSqlLo=,tag:8zmmZn0n5gSTyNARRnIffA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w25xrwp4207snq0nr7ext6slkph3n5zw0u6t358k46p7v9zx0udstxpw5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4N0ViNjBOWlBpSnNKMG5s
            VHlETU1UdHl1YzJLZzhzNUxHZGZhb1p2Sm5RClVraVYwcm9ZR2ZpUS9XSEFOSkNr
            aGdVZHRoY1FtanJzUXJSMmlMbERmVTgKLS0tIE1iTHpqd3RYMktSN08zOHhjY3lW
            ekNtU3d6amdmMU5oTW1LbFk3SS9oMzAKgpXb0scKVNFG+GGcO/x8i04zgJNzgt11
            ibn+3pRmIJAq82dWr0DLvaGagLCTAg1EOI845WECN43rktXFRQuqBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T22:48:42Z"
    mac: ENC[AES256_GCM,data:BFcD7B1MWpheuyBZNABrFHdyb92anKzlX/NzPq4yCYsMNwPmNywl6OUiES/EPIBrx/07mNTamso2jV0XfGDZ2vXVBHO1nR72rCYxy2vzCFh9Nr7sQSU29yqyvTqNHA+ZWTp6y6KjEDDXMgvgNIJ6olCSNaGk+KhtfRfuQIRMm1M=,iv:i80svrgSD7NNGWqtpcT95UsIJyVxTPqGaas7+3Ciby0=,tag:CG9lMPJwXeoMs3W1Aygi7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: calibre-web
spec:
    interval: 1m0s
    url: https://github.com/cleroux-dev-homelab/flux-apps.git
    ref:
        branch: main
    secretRef:
        name: calibre-web
    ignore: |
        /*
        !/components/books/calibre-web
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w25xrwp4207snq0nr7ext6slkph3n5zw0u6t358k46p7v9zx0udstxpw5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4N0ViNjBOWlBpSnNKMG5s
            VHlETU1UdHl1YzJLZzhzNUxHZGZhb1p2Sm5RClVraVYwcm9ZR2ZpUS9XSEFOSkNr
            aGdVZHRoY1FtanJzUXJSMmlMbERmVTgKLS0tIE1iTHpqd3RYMktSN08zOHhjY3lW
            ekNtU3d6amdmMU5oTW1LbFk3SS9oMzAKgpXb0scKVNFG+GGcO/x8i04zgJNzgt11
            ibn+3pRmIJAq82dWr0DLvaGagLCTAg1EOI845WECN43rktXFRQuqBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T22:48:42Z"
    mac: ENC[AES256_GCM,data:BFcD7B1MWpheuyBZNABrFHdyb92anKzlX/NzPq4yCYsMNwPmNywl6OUiES/EPIBrx/07mNTamso2jV0XfGDZ2vXVBHO1nR72rCYxy2vzCFh9Nr7sQSU29yqyvTqNHA+ZWTp6y6KjEDDXMgvgNIJ6olCSNaGk+KhtfRfuQIRMm1M=,iv:i80svrgSD7NNGWqtpcT95UsIJyVxTPqGaas7+3Ciby0=,tag:CG9lMPJwXeoMs3W1Aygi7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
