---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-config
data:
  ALLOW_SIGNUP: "false"
  PUID: "1000"
  PGID: "1000"
  TZ: ${TIMEZONE}
  MAX_WORKERS: "1"
  WEB_CONCURRENCY: "1"
  BASE_URL: https://mealie.${EXTERNAL_DOMAIN}
