---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  labels:
    app: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: mealie-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: mealie-postgres-app
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mealie-postgres-app
            - name: POSTGRES_SERVER
              valueFrom:
                secretKeyRef:
                  key: host
                  name: mealie-postgres-app
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: mealie-postgres-app
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: dbname
                  name: mealie-postgres-app
          ports:
            - name: mealie
              containerPort: 9000
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mealie
      restartPolicy: Always
