apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mealie
spec:
  targetNamespace: mealie
  interval: 1m0s
  retryInterval: 30s
  timeout: 30s
  path: components/recipes/mealie/controller/base
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: mealie
  images:
    - name: mealie
      newName: ghcr.io/mealie-recipes/mealie # {"$imagepolicy": "mealie:mealie:name"}
      newTag: v2.2.0 # {"$imagepolicy": "mealie:mealie:tag"}
