apiVersion: v1
kind: Secret
metadata:
    name: mealie
stringData:
    username: ENC[AES256_GCM,data:cs6Zb7R8/CqjSC7YeHvKqqnRdMOW,iv:Mk3V/Hixqi4B7cAsV5SnQw7A31+wCVYe05soyl53gas=,tag:YON7axthgQ/AlFoc9Yol9w==,type:str]
    password: ENC[AES256_GCM,data:bJ/FnisFf7hd7thefRGZbILXrqce77ijJXYG/z+0Ahk+k8/hEBP237gY3e7xnS0rFaFTFMN7y27Mr3AA9wAjsUPorwAzKGXykCkp1W/QACsRHVQc98wMKYGkjdVe,iv:4tiOTctscmj6Rgg46X0NnLcO1cYLy/2zf13kDvWFyPU=,tag:a7A2caPhqz62fBpfH6UWFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w25xrwp4207snq0nr7ext6slkph3n5zw0u6t358k46p7v9zx0udstxpw5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOFNmeFQrSXl0TzZITkhJ
            QWxsUW9sdkk2bW81K2x6WE1XUVpKQjd2b0ZFCmV5UWRYS1NJUGpTMHh0VDRLQ2lP
            NGRmczAySUNWRW9iSHVmalJRNmZpVDAKLS0tIHNiWXA0MEpMazNBUVI0UWFpZkkz
            aTFYQnNLdHdkZnYzZVExWGNuSGhTRFEKiaPppsthtOQjm9itF0kwA+zHQ7YVVJp0
            mQ9gcflsW1dXd2dtMoGZUmCRf7G3QWZU0K9PCwx8eeSy1n8wqAfOTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T22:48:23Z"
    mac: ENC[AES256_GCM,data:rkonVvtC16uH5OVfyVWCD2Ya4RfSH4ykClBfp2sXDycmoeeIBD8DcDo74vctoiCrBL/s3x0yg+MV+GAmjXrjD11pkx24pWDZd5g6jVEMkLHrPRV7GweTozctzowRIE3PQkXkHuMI2Rf7x8CxAt4DnoiGfEo/KDRiI58aFXMimMw=,iv:Fq5h0W91DAXnfUu2CnwgCQh8DfNQfbRGKZr4E4aEw2c=,tag:1EbSUqFY+GRE8d38Y6Kxsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: mealie
spec:
    interval: 1m0s
    url: https://github.com/cleroux-dev-homelab/flux-apps.git
    ref:
        branch: main
    secretRef:
        name: mealie
    ignore: |
        # exclude all
        /*
        !/components/recipes/mealie
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w25xrwp4207snq0nr7ext6slkph3n5zw0u6t358k46p7v9zx0udstxpw5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOFNmeFQrSXl0TzZITkhJ
            QWxsUW9sdkk2bW81K2x6WE1XUVpKQjd2b0ZFCmV5UWRYS1NJUGpTMHh0VDRLQ2lP
            NGRmczAySUNWRW9iSHVmalJRNmZpVDAKLS0tIHNiWXA0MEpMazNBUVI0UWFpZkkz
            aTFYQnNLdHdkZnYzZVExWGNuSGhTRFEKiaPppsthtOQjm9itF0kwA+zHQ7YVVJp0
            mQ9gcflsW1dXd2dtMoGZUmCRf7G3QWZU0K9PCwx8eeSy1n8wqAfOTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T22:48:23Z"
    mac: ENC[AES256_GCM,data:rkonVvtC16uH5OVfyVWCD2Ya4RfSH4ykClBfp2sXDycmoeeIBD8DcDo74vctoiCrBL/s3x0yg+MV+GAmjXrjD11pkx24pWDZd5g6jVEMkLHrPRV7GweTozctzowRIE3PQkXkHuMI2Rf7x8CxAt4DnoiGfEo/KDRiI58aFXMimMw=,iv:Fq5h0W91DAXnfUu2CnwgCQh8DfNQfbRGKZr4E4aEw2c=,tag:1EbSUqFY+GRE8d38Y6Kxsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
