apiVersion: v1
kind: Secret
metadata:
    name: mealie
stringData:
    username: ENC[AES256_GCM,data:9ggT59Vec9BL/bRVgw0q+x7W56bf,iv:ZrjiAta5g9gma2v1aDcP9vsVg/ZCwCndVTU0Km+ESIY=,tag:SyJ5g/ZASw06JJngxIDWNQ==,type:str]
    password: ENC[AES256_GCM,data:uHy5TiWSkANI/lxB009YWrDzIFwT5fEib0LZbLKGI/7QYSHutX7S7LPoYGrzvSOF1EU/eAw5bsOkWdSa/mhspr8Ns173XDOSJgoHJ9OhpJ0nsDG6cBX6rD34Swbb,iv:5Wu4EkGobTAA7270iwt73l2er6Pm//FSefC6PwrNzzU=,tag:BHSsZLo9sbFklWiR7F/nPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w25xrwp4207snq0nr7ext6slkph3n5zw0u6t358k46p7v9zx0udstxpw5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2alUzTGZRUG90MmJqd3I1
            OUpFYXJSUkNPYUw4OFZJWEV1R3dhWG10am1ZCnVWWTlMSzVxZVlxTVVFZEZaWkkr
            UDBwQTlwTlZDcU5GaVZxVDRJZG1JVVUKLS0tIHQzOVFuSlhoVUNJWjkvbytza2ow
            by9idUs5MkVSNThTVllHT0UveGR5b0EKYHnLQU54f6TmES61yno4EM4RX0qDUKUK
            7M3Ajt8I5iHtUs/W9z8FVNOr5pX4Ptvm197xKLny+IY1RDv1dEfpAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T22:34:35Z"
    mac: ENC[AES256_GCM,data:X5CR8tDTAMLq5KhZYsa55vTFDmLQraxhakp6I2iuX54HFPq3YS+QywwoGFRQk8c43Ym7BVx5kk2C+mnrFe5weYcvOsXVLKbVWSdO+NQyvwIa601iQyRfakQOtOFnwo2vJZzB5eq3MJWU+B2uhAsopZqcNbmYmWjKdtJAbWblX1g=,iv:42VoFXhdqCLK/tCAL4B+xnYyel2kwiEt83gn1YHhHuw=,tag:pA4dFet+aXcO1PI2EddQ2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: mealie
spec:
    interval: 1m0s
    url: https://github.com/cleroux-dev-homelab/flux-apps.git
    ref:
        branch: main
    secretRef:
        - name: mealie
    ignore: |
        # exclude all
        /*
        !/components/recipes/mealie
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w25xrwp4207snq0nr7ext6slkph3n5zw0u6t358k46p7v9zx0udstxpw5c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2alUzTGZRUG90MmJqd3I1
            OUpFYXJSUkNPYUw4OFZJWEV1R3dhWG10am1ZCnVWWTlMSzVxZVlxTVVFZEZaWkkr
            UDBwQTlwTlZDcU5GaVZxVDRJZG1JVVUKLS0tIHQzOVFuSlhoVUNJWjkvbytza2ow
            by9idUs5MkVSNThTVllHT0UveGR5b0EKYHnLQU54f6TmES61yno4EM4RX0qDUKUK
            7M3Ajt8I5iHtUs/W9z8FVNOr5pX4Ptvm197xKLny+IY1RDv1dEfpAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T22:34:35Z"
    mac: ENC[AES256_GCM,data:X5CR8tDTAMLq5KhZYsa55vTFDmLQraxhakp6I2iuX54HFPq3YS+QywwoGFRQk8c43Ym7BVx5kk2C+mnrFe5weYcvOsXVLKbVWSdO+NQyvwIa601iQyRfakQOtOFnwo2vJZzB5eq3MJWU+B2uhAsopZqcNbmYmWjKdtJAbWblX1g=,iv:42VoFXhdqCLK/tCAL4B+xnYyel2kwiEt83gn1YHhHuw=,tag:pA4dFet+aXcO1PI2EddQ2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
