---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actual-server

resources:
  - ../../../bases/actual-server
  - ./ingress.yaml

patches:
  - path: version.yaml
    target:
      kind: Deployment
      name: actual-server
